@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Feb 13 08:58:54 +0900 2026
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_sr04_behav -key {Behavioral:sim_1:Functional:tb_sr04} -tclbatch tb_sr04.tcl -view D:/workplace/Ondevice/project_2_uart_sensor_stopwatch_watch/tb_sr04_behav.wcfg -log simulate.log"
call xsim  tb_sr04_behav -key {Behavioral:sim_1:Functional:tb_sr04} -tclbatch tb_sr04.tcl -view D:/workplace/Ondevice/project_2_uart_sensor_stopwatch_watch/tb_sr04_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
